// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  MediaState,
} from "./types";


export default __t.row({
  participantId: __t.u64().primaryKey().name("participant_id"),
  roomId: __t.u64().name("room_id"),
  identity: __t.identity(),
  displayName: __t.string().name("display_name"),
  joinedAt: __t.timestamp().name("joined_at"),
  leftAt: __t.option(__t.timestamp()).name("left_at"),
  isHost: __t.bool().name("is_host"),
  get mediaState() {
    return MediaState.name("media_state");
  },
});
