// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  RoomStatus,
} from "./types";


export default __t.row({
  roomId: __t.u64().primaryKey().name("room_id"),
  roomCode: __t.string().name("room_code"),
  title: __t.string(),
  hostIdentity: __t.identity().name("host_identity"),
  get status() {
    return RoomStatus;
  },
  createdAt: __t.timestamp().name("created_at"),
  endedAt: __t.option(__t.timestamp()).name("ended_at"),
});
