// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const ChatRateLimit = __t.object("ChatRateLimit", {
  identity: __t.identity(),
  lastMessageAt: __t.timestamp(),
});
export type ChatRateLimit = __Infer<typeof ChatRateLimit>;

// The tagged union or sum type for the algebraic type `EventType`.
export const EventType = __t.enum("EventType", {
  MeetingStarted: __t.unit(),
  ParticipantJoined: __t.unit(),
  ParticipantLeft: __t.unit(),
  MediaToggled: __t.unit(),
  MeetingEnded: __t.unit(),
  ChatMessage: __t.unit(),
  ReactionSent: __t.unit(),
});
export type EventType = __Infer<typeof EventType>;

export const MediaState = __t.object("MediaState", {
  audioEnabled: __t.bool(),
  videoEnabled: __t.bool(),
  isScreenSharing: __t.bool(),
  get presenceStatus() {
    return PresenceStatus;
  },
});
export type MediaState = __Infer<typeof MediaState>;

export const Participant = __t.object("Participant", {
  participantId: __t.u64(),
  roomId: __t.u64(),
  identity: __t.identity(),
  displayName: __t.string(),
  joinedAt: __t.timestamp(),
  leftAt: __t.option(__t.timestamp()),
  isHost: __t.bool(),
  get mediaState() {
    return MediaState;
  },
});
export type Participant = __Infer<typeof Participant>;

// The tagged union or sum type for the algebraic type `PresenceStatus`.
export const PresenceStatus = __t.enum("PresenceStatus", {
  Unknown: __t.unit(),
  Active: __t.unit(),
  Away: __t.unit(),
  Drowsy: __t.unit(),
});
export type PresenceStatus = __Infer<typeof PresenceStatus>;

export const Room = __t.object("Room", {
  roomId: __t.u64(),
  roomCode: __t.string(),
  title: __t.string(),
  hostIdentity: __t.identity(),
  get status() {
    return RoomStatus;
  },
  createdAt: __t.timestamp(),
  endedAt: __t.option(__t.timestamp()),
});
export type Room = __Infer<typeof Room>;

export const RoomEvent = __t.object("RoomEvent", {
  eventId: __t.u64(),
  roomId: __t.u64(),
  get eventType() {
    return EventType;
  },
  payload: __t.string(),
  timestamp: __t.timestamp(),
  identity: __t.identity(),
});
export type RoomEvent = __Infer<typeof RoomEvent>;

// The tagged union or sum type for the algebraic type `RoomStatus`.
export const RoomStatus = __t.enum("RoomStatus", {
  Waiting: __t.unit(),
  Active: __t.unit(),
  Ended: __t.unit(),
});
export type RoomStatus = __Infer<typeof RoomStatus>;

export const SignalingMessage = __t.object("SignalingMessage", {
  id: __t.u64(),
  roomId: __t.u64(),
  fromIdentity: __t.identity(),
  toIdentity: __t.identity(),
  get messageType() {
    return SignalingMessageType;
  },
  payload: __t.string(),
  createdAt: __t.timestamp(),
});
export type SignalingMessage = __Infer<typeof SignalingMessage>;

// The tagged union or sum type for the algebraic type `SignalingMessageType`.
export const SignalingMessageType = __t.enum("SignalingMessageType", {
  Offer: __t.unit(),
  Answer: __t.unit(),
  IceCandidate: __t.unit(),
});
export type SignalingMessageType = __Infer<typeof SignalingMessageType>;

export const User = __t.object("User", {
  identity: __t.identity(),
  displayName: __t.string(),
  createdAt: __t.timestamp(),
});
export type User = __Infer<typeof User>;

