// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import CleanupSignalingReducer from "../cleanup_signaling_reducer";
import CreateRoomReducer from "../create_room_reducer";
import EndMeetingReducer from "../end_meeting_reducer";
import GetTurnCredentialsReducer from "../get_turn_credentials_reducer";
import JoinRoomReducer from "../join_room_reducer";
import LeaveRoomReducer from "../leave_room_reducer";
import SendAnswerReducer from "../send_answer_reducer";
import SendChatMessageReducer from "../send_chat_message_reducer";
import SendIceCandidateReducer from "../send_ice_candidate_reducer";
import SendOfferReducer from "../send_offer_reducer";
import SendReactionReducer from "../send_reaction_reducer";
import UpdateMediaStateReducer from "../update_media_state_reducer";
import UpdatePresenceStatusReducer from "../update_presence_status_reducer";

export type CleanupSignalingParams = __Infer<typeof CleanupSignalingReducer>;
export type CreateRoomParams = __Infer<typeof CreateRoomReducer>;
export type EndMeetingParams = __Infer<typeof EndMeetingReducer>;
export type GetTurnCredentialsParams = __Infer<typeof GetTurnCredentialsReducer>;
export type JoinRoomParams = __Infer<typeof JoinRoomReducer>;
export type LeaveRoomParams = __Infer<typeof LeaveRoomReducer>;
export type SendAnswerParams = __Infer<typeof SendAnswerReducer>;
export type SendChatMessageParams = __Infer<typeof SendChatMessageReducer>;
export type SendIceCandidateParams = __Infer<typeof SendIceCandidateReducer>;
export type SendOfferParams = __Infer<typeof SendOfferReducer>;
export type SendReactionParams = __Infer<typeof SendReactionReducer>;
export type UpdateMediaStateParams = __Infer<typeof UpdateMediaStateReducer>;
export type UpdatePresenceStatusParams = __Infer<typeof UpdatePresenceStatusReducer>;

